[[bond]]
source = "tpknam1qrw6rfshklssfz7kws9gj9ggujhtv4c0caruh945uwrxaxjpj9wzwlss4xh"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "270"

[bond.signatures]
tpknam1qrw6rfshklssfz7kws9gj9ggujhtv4c0caruh945uwrxaxjpj9wzwlss4xh = "signam1qrdsck6lnp3vyumugsx4m9ce9ww378ra66k59ezrm5ln8zu9uwk7dyjwn60tvu4pwvy6hvpmglj7ghxzvey2fhsrk4zxpucysxgeu7srd4s9cw"
